# Generated by Django 5.1.1 on 2024-09-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("profile", models.TextField()),
                ("date_of_birth", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lyricists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("profile", models.TextField()),
                ("date_of_birth", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("duration", models.CharField(max_length=10)),
                ("genre", models.CharField(max_length=100)),
                ("album_name", models.CharField(max_length=200)),
                (
                    "artists",
                    models.ManyToManyField(
                        related_name="music_artists", to="music_review_app.artists"
                    ),
                ),
                (
                    "composed_by",
                    models.ManyToManyField(
                        related_name="music_compositions", to="music_review_app.artists"
                    ),
                ),
                (
                    "lyricist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lyrics_writer",
                        to="music_review_app.lyricists",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                (
                    "music",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_review",
                        to="music_review_app.music",
                    ),
                ),
            ],
        ),
    ]
